owner: ImJferrer
repo: ViewPAM

sites:
  - name: PAM - Server
    url: https://zeus.fiberlux.pe/healt

status-website:
  name: Estado del sistema
  introTitle: "Estado del servidor"
  introMessage: "Monitoreo automático del sistema"
